#!/usr/bin/env sh

# Setup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.2
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          8
yabai -m config active_window_border_color   0x999999ff
yabai -m config normal_window_border_color   0xAARRGGBB
yabai -m config insert_feedback_color        0xAARRGGBB
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# General space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   10

# Spacebar (top bar)
# SPACEBAR_HEIGHT=$(spacebar -m config height)
# yabai -m config external_bar                 all:$SPACEBAR_HEIGHT:0

# Defaults for spaces
yabai -m config --space 2 layout                stack
yabai -m config --space 2 top_padding           0
yabai -m config --space 2 bottom_padding        0
yabai -m config --space 2 left_padding          0
yabai -m config --space 2 right_padding         0
yabai -m config --space 2 window_gap            0

## RULES
yabai -m rule --add app="^Discord$"            opacity=1
yabai -m rule --add app="^Franz$"              opacity=1
yabai -m rule --add app="^Telegram$"           opacity=1
yabai -m rule --add app="^Finder$"             opacity=1
yabai -m rule --add app="^Vivaldi$"            opacity=1
yabai -m rule --add app="^Spotify$"            opacity=1
yabai -m rule --add app="^TeamViewer$"         opacity=1
yabai -m rule --add app="^Sublime Merge$"      opacity=1
yabai -m rule --add app="^Sublime Text$"       opacity=1

# Manage
yabai -m rule --add app="^System Preferences$" opacity=1 manage=off
yabai -m rule --add app="^App Store$"          opacity=1 manage=off
yabai -m rule --add app="^Activity Monitor$"   opacity=1 manage=off
yabai -m rule --add app="^Preview$"            opacity=1 manage=off
yabai -m rule --add app="^iStat Menus Status$" opacity=1 manage=off
yabai -m rule --add app='^Little Snitch$'      opacity=1 manage=off
yabai -m rule --add app="^zoom.us$"            opacity=1 manage=off
yabai -m rule --add app="^Dropbox Passwords$"  opacity=1 manage=off
yabai -m rule --add app="^Airmail$"            opacity=1 manage=off
yabai -m rule --add app="^Authy Desktop$"      opacity=1 manage=off
yabai -m rule --add app="^Contexts$"           opacity=1 manage=off
yabai -m rule --add app="^Docker Desktop$"     opacity=1 manage=off

echo "yabai configuration loaded.."
