sourceDir = "/Users/fagarnovoa/dev/dotfiles"
color     = true
follow    = true
verbose   = true
format    = "yaml"

[diff]
  format = "git"

[gpg]
  recipient = "rojo@rojo.dev"
  args      = "--quiet"

[git]
  autoAdd     = true
  autoCommit  = true
  autoPush    = true
